### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by KaleyMoro** [CryShana/Sankaku-Channel-Downloader#11]
Can't Login in new release, it always says failed to login.
![image](https://user-images.githubusercontent.com/39103357/40006979-68524c38-57bb-11e8-8326-85be2280dccb.png)

**Comment by CryShana** [comment]
That is weird. It seems to be working fine for me on different devices using different accounts. Are you sure you are using the correct credentials? Otherwise I am planning on implementing some logging to log these errors.

**Comment by DreamPhreak** [comment]
Had the same issue. Tried downloading version 1.1 (previous version), still couldn't log in. Then downloaded 1.0.6 and logs in just fine.

Also with the overhaul versions, trying to download without logging in gives this error: https://i.imgur.com/D1em2Ug.png

**Comment by CryShana** [comment]
Please go check the 1.1.2 release. I added error logging now and you should no longer be getting the missing "System.Net.Http" error. As for logging in - I would like you to post the error log after failing to log in.

**Comment by DreamPhreak** [comment]
`[15.05.2018 07:10:00] btnLogin_Click error -> {"reason":"Invalid appkey supplied","success":false,"result":"invalid-appkey"}`

Even though I'm 100% sure my login is correct. Logged into the website with my login just fine, and then changed my password to a generated one with only lowercase letters and numbers instead of symbols like before, then the required me to login in again with the newly changed password and worked fine. Then immediately went to the app and can't login.

Also a quick warning: Your 1.1.2 includes your own settings file which has your login, and the app automatically logs in as you. But it's interesting that it logs in as you, but can't as me. The sankaku site doesn't have a special API key or anything of that sort, right?

**Comment by CryShana** [comment]
Thanks for the settings warning. Yeah I thought it was the appkey - I believe the appkey gets generated by the client - but I need to confirm. Will try to fix it asap.

**Comment by CryShana** [comment]
Try out the 1.1.3 release. AppKey is now being generated per user

**Comment by KaleyMoro** [comment]
Thanks it's fixed in latest release :D but it has some Graphical error in success dialogue box
