### ISSUE TITLE
Task Finished in the MIDDLE

### ISSUE THREAD

**Issue by KaleyMoro** [CryShana/Sankaku-Channel-Downloader#14]
it says the task is finished out of no where when lots of image is still remaining to download. and sometimes it doesn't even bother to start downloading all it says is "task finished".

![image](https://user-images.githubusercontent.com/39103357/40248598-2f1fed34-5af0-11e8-8dd1-694de8030d5a.png)

**Comment by CryShana** [comment]
Alright. Will check it out later. If you can, could you tell me the settings and query you used to get this - does this happen every time with the same settings or is it random?

**Comment by KaleyMoro** [comment]
Well, It doesn't happen everytime but I guess when i use multiple tags to download it happens, It happend when i was using "High_school_DxD Dakimakura" and some other times too! And when I deleted all those Files and restarted the task it downloaded all that time :)



![image](https://user-images.githubusercontent.com/39103357/40367658-a7cbeed4-5df9-11e8-99ea-66c2eec3645a.png)

**Comment by CryShana** [comment]
I am still unable to reproduce the issue. Try out the new release 1.1.5 and if the issue still persists, please attach an image of the error log (if it got generated at all)

**Comment by Alkl58** [comment]
I also have this bug. 

Exactly the same notification, that the task has been finished. Furthermore I also get partially the error message as log file (german):

> [11.07.2018 20:11:09] StartDownloading() exception -> Mindestens ein Fehler ist aufgetreten. -> Eine Aufgabe wurde abgebrochen.
> [11.07.2018 20:11:09] Download error -> Mindestens ein Fehler ist aufgetreten. -> Eine Aufgabe wurde abgebrochen.

Translated: 
> [11.07.2018 20:11:09] StartDownloading () exception -> At least one error has occurred. -> The task has been canceled.

I also once had the following error: 

> [09.07.2018 17:45:50] HttpError - Trying again in 0 second/s -> Fehler beim Kopieren von Inhalt in einen Stream. -> Von der Übertragungsverbindung können keine Daten gelesen werden: Eine vorhandene Verbindung wurde vom Remotehost geschlossen. -> Eine vorhandene Verbindung wurde vom Remotehost geschlossen

Translated:

> [09.07.2018 17:45:50] HttpError - Trying again in 0 second / s -> Error copying content into a stream. -> Data can not be read from the transmission connection: An existing connection was closed by the remote host. -> An existing connection was closed by the remote host

At the moment Im in vacation with my notebook. (Windows 10 64x Home)
Back at home in germany I had no poblems using it with up to 6 downloads simultaneously. Perhaps it has to do something with the ip-Adress, because at home I have ipv6 and here in vacation (greek) ipv4. No changement with VPN.

Disabling the antivirus didn't helped...

![000](https://user-images.githubusercontent.com/34812414/42595694-5642e960-8553-11e8-8c31-98eb5f85a9e6.jpg)

**Comment by CryShana** [comment]
Thank you for the error log. I will look into it when I get the time and report back. If you notice any new errors, post them here.

**Comment by CryShana** [comment]
I have identified the bug and fixed it.
https://github.com/CryShana/Sankaku-Channel-Downloader/releases/tag/1.1.7

I've tested it a bit myself, but do give it a try and report if the issue persists.
