### ISSUE TITLE
download speed

### ISSUE THREAD

**Issue by J3loodz** [CryShana/Sankaku-Channel-Downloader#16]
is it actually possible to increase the download speed im not familiar with this

**Comment by CryShana** [comment]
yes, it is possible to speed it up a **little bit** by concurrently downloading some files instead of sequentially. But I'm not sure whether it's a good idea since Sankaku Channel can block you fairly quickly if you download stuff from their site too quickly. (at least that was the case with the old API)

I will try experimenting with it and possibly add an option for concurrent downloads. I will let you know when I implement it.

**Comment by J3loodz** [comment]
thanks thas nice from you

2018-06-12 10:08 GMT+02:00 Adam Veselič <notifications@github.com>:

**Comment by CryShana** [comment]
I have added a "Concurrent Downloads" checkbox in the latest commit. It is still very experimental, so I will not yet add it to the Releases until I test it more.

**Comment by CryShana** [comment]
Here you go. Try out this release:
https://github.com/CryShana/Sankaku-Channel-Downloader/releases/tag/1.1.6

Keep in mind this is experimental and might cause issues. I fixed most of them that appeared for me but didn't test it extensively.
